/* Project3.java
 * Jonathan Mainhart
 * CMIS 242
 * GUI presents options for users to build shapes and display them in a frame. 
 */
package mainhart;

import java.awt.Color;
import java.awt.Rectangle;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jonmainhart
 */
public class Project3 extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Project3
     */
    public Project3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shapeTypeLabel = new javax.swing.JLabel();
        fillTypeLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        widthLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        coordinateXLabel = new javax.swing.JLabel();
        coordinateYLabel = new javax.swing.JLabel();
        shapeTypeCombo = new javax.swing.JComboBox<>();
        fillTypeCombo = new javax.swing.JComboBox<>();
        colorCombo = new javax.swing.JComboBox<>();
        widthText = new javax.swing.JTextField();
        heightText = new javax.swing.JTextField();
        coordinateXText = new javax.swing.JTextField();
        coordinateYText = new javax.swing.JTextField();
        drawButton = new javax.swing.JButton();
        shapeDrawingPanel = new mainhart.Drawing();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geometric Drawing");

        shapeTypeLabel.setText("Shape Type");

        fillTypeLabel.setText("Fill Type");

        colorLabel.setText("Color");

        widthLabel.setText("Width");

        heightLabel.setText("Height");

        coordinateXLabel.setText("x coordinate");

        coordinateYLabel.setText("y coordinate");

        shapeTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rectangle", "Oval" }));

        fillTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hollow", "Solid" }));

        colorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "Red", "Orange", "Yellow", "Green", "Blue", "Magenta" }));

        drawButton.setText("Draw");
        drawButton.setAlignmentY(0.0F);
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        shapeDrawingPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true), "Shape Drawing"), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        shapeDrawingPanel.setToolTipText("");
        shapeDrawingPanel.setMaximumSize(new java.awt.Dimension(200, 200));
        shapeDrawingPanel.setName(""); // NOI18N

        javax.swing.GroupLayout shapeDrawingPanelLayout = new javax.swing.GroupLayout(shapeDrawingPanel);
        shapeDrawingPanel.setLayout(shapeDrawingPanelLayout);
        shapeDrawingPanelLayout.setHorizontalGroup(
            shapeDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        shapeDrawingPanelLayout.setVerticalGroup(
            shapeDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(drawButton)
                .addContainerGap(261, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shapeTypeLabel)
                    .addComponent(fillTypeLabel)
                    .addComponent(colorLabel)
                    .addComponent(widthLabel)
                    .addComponent(heightLabel)
                    .addComponent(coordinateXLabel)
                    .addComponent(coordinateYLabel))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shapeTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fillTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(widthText)
                    .addComponent(heightText)
                    .addComponent(coordinateXText)
                    .addComponent(coordinateYText))
                .addGap(18, 18, 18)
                .addComponent(shapeDrawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {colorCombo, fillTypeCombo, shapeTypeCombo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(shapeTypeLabel)
                        .addGap(29, 29, 29)
                        .addComponent(fillTypeLabel)
                        .addGap(29, 29, 29)
                        .addComponent(colorLabel)
                        .addGap(30, 30, 30)
                        .addComponent(widthLabel)
                        .addGap(28, 28, 28)
                        .addComponent(heightLabel)
                        .addGap(28, 28, 28)
                        .addComponent(coordinateXLabel)
                        .addGap(28, 28, 28)
                        .addComponent(coordinateYLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shapeTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fillTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(colorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(widthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(coordinateXText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(coordinateYText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(shapeDrawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(drawButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed
        /* When the button is clicked an instance of a shape object will be
           created and passed to the shapeDrawingPanel.drawShape() method.
           Exception handling included to ensure all fields are filled.
         */

        try {
            Shape s = shapeBuilder();
            shapeDrawingPanel.drawShape(s);

        } catch (NumberFormatException nfe) {
            System.out.println("Exception Thrown " + nfe.getMessage());
            // popup user message
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,
                    "You Must Enter Whole Numbers for Coordinates and Dimensions.");
        }

    }//GEN-LAST:event_drawButtonActionPerformed
    // end drawButtonActionPerformed

    private Shape shapeBuilder() {
        /* creates a rectangle from the user input, sends that basic shape along
           with the other input variables to the appropriate constructor and 
           returns a Shape object of the correct type.
         */

        // create a new rectangle for Oval or Rectangular constructor  
        Rectangle rect = new Rectangle(Integer.parseInt(coordinateXText.getText()),
                Integer.parseInt(coordinateYText.getText()), Integer.parseInt(widthText.getText()),
                Integer.parseInt(heightText.getText()));

        // create a boolean value from the comboBox selection
        boolean filled = false; // default is not filled
        if (fillTypeCombo.getSelectedItem().toString().equalsIgnoreCase("solid")) {
            filled = true;
        }

        // Shape color is selected from the combo box
        Color colorValue = getColorValue();

        // create the user selected shape
        if (shapeTypeCombo.getSelectedItem().toString().equalsIgnoreCase("rectangle")) {
            return new Rectangular(rect,
                    colorValue,
                    filled);
        } else {
            return new Oval(rect,
                    colorValue,
                    filled);
        }

    } // end shapeBuilder

    private Color getColorValue() {
        // in the interest of trying to keep things readable
        // Gets user selected color
        switch (colorCombo.getSelectedIndex()) {
            case 0:
                return Color.BLACK;
            case 1:
                return Color.RED;
            case 2:
                return Color.ORANGE;
            case 3:
                return Color.YELLOW;
            case 4:
                return Color.GREEN;
            case 5:
                return Color.BLUE;
            default:
                return Color.MAGENTA;
        }
    } // end color selection

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Project3().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> colorCombo;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JLabel coordinateXLabel;
    private javax.swing.JTextField coordinateXText;
    private javax.swing.JLabel coordinateYLabel;
    private javax.swing.JTextField coordinateYText;
    private javax.swing.JButton drawButton;
    private javax.swing.JComboBox<String> fillTypeCombo;
    private javax.swing.JLabel fillTypeLabel;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightText;
    private mainhart.Drawing shapeDrawingPanel;
    private javax.swing.JComboBox<String> shapeTypeCombo;
    private javax.swing.JLabel shapeTypeLabel;
    private javax.swing.JLabel widthLabel;
    private javax.swing.JTextField widthText;
    // End of variables declaration//GEN-END:variables
}
